import './globals.css'
import { Montserrat } from 'next/font/google'
import styles from './page.module.css'

const montserrat = Montserrat({ subsets: ['latin'], weight: ['300'] })

export const metadata = {
  title: 'Deal Acres',
  description: 'Generated by create next app',
  
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles.container}>
        <main className={montserrat.className}>
          {children}
          </main>
        </body>
    </html>
  )
}
